// <auto-generated />
using System;
using EfCoreApp01;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EfCoreApp01.Migrations
{
    [DbContext(typeof(IncedoDbContext))]
    [Migration("20211027052742_migration1")]
    partial class migration1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EfCoreApp01.Department", b =>
                {
                    b.Property<int>("DId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DId");

                    b.ToTable("tblDepartments");

                    b.HasData(
                        new
                        {
                            DId = 10,
                            DName = "Software",
                            Location = "USA"
                        },
                        new
                        {
                            DId = 20,
                            DName = "Hardware",
                            Location = "UK"
                        });
                });

            modelBuilder.Entity("EfCoreApp01.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DId1")
                        .HasColumnType("int");

                    b.Property<string>("EName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Job")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DId1");

                    b.ToTable("tblEmployees");

                    b.HasData(
                        new
                        {
                            Id = 1001,
                            EName = "Kiran",
                            Job = "Trainer",
                            Salary = 5000
                        },
                        new
                        {
                            Id = 1002,
                            EName = "Raju",
                            Job = "Developer",
                            Salary = 6000
                        });
                });

            modelBuilder.Entity("EfCoreApp01.Employee", b =>
                {
                    b.HasOne("EfCoreApp01.Department", "DId")
                        .WithMany("Employee")
                        .HasForeignKey("DId1");
                });
#pragma warning restore 612, 618
        }
    }
}
